### ISSUE TITLE
Consider a Map analogue?

### ISSUE THREAD

**Issue by ajvincent** [tc39/proposal-await-dictionary#11]
Note: I'm only filing this for discussion purposes, not necessarily because I think it's a good idea.  Specifically, the "Q&A" part of the README implies we looked at `Map` - which we did two years ago, but we haven't captured anywhere in the proposal text.

**Comment by ljharb** [comment]
Based on the discussion in the array grouping proposal, I think it's pretty clear and understood that objects are more ergonomic, and that Map only comes into play when there's a distinct advantage from using it. Since the ergonomic goal here is for object destructuring, which doesn't work with Maps, I think there's just no direction here to go.

**Comment by ajvincent** [comment]
Then maybe we just need to update the Q&A section.
